### ISSUE TITLE
Error: cound not connect to the endpoint URL

### ISSUE THREAD

**Issue by TBondat** [EscVM/OIDv4_ToolKit#10]
This toolkit looks very useful to extract parts of Open image!!
I work on windows 7 (sorry), python 3.6.
When i try to launch the basic command line you provide:
`python main.py downloader --classes Apple Orange --type_csv validation`

i get first a bunch of lines saying "File association not found for extension .py" , and in between,
for each image it tries to pick "fatal error: cound not commect to the endpoint URL: "https://open-images...."
At the end of the process, of course, i get empty folders where the pictures should be.

I don't know for the file association message, but for the second error, it seems to be because of my proxy. Is there an option to add in command line the proxy? that would be very useful. Like what we can see in other dataset downloader, `--proxy "http:XXXXXXXX:port"`

or where can i hardcode proxy information in the python files of the toolkit?

thanks

**Comment by EscVM** [comment]
Hi @TBondat ,
have you installed the requirements with the command `pip3 install -r requirements.txt`?

**Comment by TBondat** [comment]
Yes, i installed all the required libs successfully using your requirement file.

**Comment by EscVM** [comment]
It could be something related with Windows 7 os or with the python3 packages installations. With windows 10, Mac Os X and Linux/GNU it works just fine. 

Regarding the proxy, why are you using a proxy server? Don't you have the possibility to connect without it?

**Comment by TBondat** [comment]
No, i cannot bypass proxy server. This is installed by my company on all our computers. According to the error message, im pretty sure it is coming from the proxy.
Typically, i need to use the option --proxy too for all pip installations. it works very well with that.
Where is done exactly the url request in the toolkit? i can maybe find an option to add proxy settings , at least.

**Comment by EscVM** [comment]
Ah ok, so it's something related to your personal situation.

You can find the code [here](https://github.com/EscVM/OIDv4_ToolKit/blob/master/modules/downloader.py) (second function). So, good luck :nerd_face:

**Comment by keldrom** [comment]
@TBondat Please help us and we'll find the problem :) 
After the installation of the requirements try to launch from your terminal this command:
`aws s3 --no-sign-request --only-show-errors cp s3://open-images-dataset/validation/41e2356b97f775c4.jpg`
followed by a path to a desired folder; if you want to download in the same folder where you've opened the terminal launch the command:
`aws s3 --no-sign-request --only-show-errors cp s3://open-images-dataset/validation/41e2356b97f775c4.jpg test_image`
Then, if it works the problem can be on our code somewhere and we'll try to find it out; instead if there are problems with proxy or anything else may you have some drama with the connection to the OIDv4 website and I think that we can, in this case, do nothing :S 
Btw please share with us the output from the terminal when you will try to use that command :)

**Comment by TBondat** [comment]
So, i found a workaround to set proxy settings directly in the session instead of giving it as toolkit arguments, it works well. So i can download pictures now, like with your command line above too.
I still have the message "File association not found for extension .py" however. depending on the pictures i can have 1, 5 or 10 times for instance, this line before it downloads the image.
If you have an idea where it comes from maybe? but i get the images so it is definitly not critical!

An other thing, when i tried to visualize the images using your nice visualizer, it works well with single-word classes like apple, it is just perfect function for quick checking!
but i got error with double word like "Traffic sign".
For the download part, i did like you advise in other page, replacing whitespace by _ , it works well but for the visualizer i didn't succeed.
I tried:
1/ Normal name with whitespace (Traffic light)=> 
Kit-master\modules\show.py", line 65, in show
    cv2.putText(img,class_name,(int(float(ax[1]))+5,int(float(ax[2]))-7), font,
0.8,(b, g, r), 2,cv2.LINE_AA)
ValueError: could not convert string to float: 'light'
2/ Using Traffic_light => Error: Images folder not found
Which has sense of course. So if now, i update the folder name with _ too,
3/ with folder and keywork Traffic_light, i get same error as in 1/

Should i replace the whitespace in all label files too? or there is an easier way.
Let me know if i should create an other topic for this visualizer problem for more clarity!

**Comment by TBondat** [comment]
thanks perfect. The toolkit is extremely valuable to work with this huge dataset!
Regarding proxy, it is fixed just by adding variable environnment for the proxy. For Windows,
`> set HTTP_PROXY=username:password@a.b.c.d:n`
`> set HTTPS_PROXY=username:password@w.x.y.z:m`

More info can be found on the dedicated page on AWS, https://docs.aws.amazon.com/cli/latest/userguide/cli-http-proxy.html
