### ISSUE TITLE
Download imgae error

### ISSUE THREAD

**Issue by sh2120170809** [EscVM/OIDv4_ToolKit#102]
[INFO] | Downloading test images.
    [INFO] | [INFO] Found 5408 online images for test.
    [INFO] | Download of 5408 images in test.
sh: 1: sh: 1: aws: not found
aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found
sh: 1: aws: not found

**Comment by netraparihar22** [comment]
How was this issue resolved?
