### ISSUE TITLE
Unable to download pictures

### ISSUE THREAD

**Issue by Jy2618** [EscVM/OIDv4_ToolKit#105]
![image](https://user-images.githubusercontent.com/102636725/180610758-708c877c-1e33-4944-be83-8d71888de2cf.png)
I do not know whether the picture has been downloaded successfully or not, as well as the location of the picture.
I tried adding the --Dataset argument to the end, but it still didn't work.

**Comment by CemEntok** [comment]
Is there any error message when you run that command?

**Comment by Jy2618** [comment]
> Is there any error message when you run that command?

I have solved the problem,thank you.

**Comment by CemEntok** [comment]
It would be perfect if you could have told how you fixed the problem though so that the community might get helped.

**Comment by Jy2618** [comment]
I

> It would be perfect if you could have told how you fixed the problem though so that the community might get helped.

I changed Python3 to Python,the problem is solved perfectly.I don't konw why,but it did.
