### ISSUE TITLE
Unable to parse the bounding boxes from train-annotations-bbox.csv file

### ISSUE THREAD

**Issue by jillelajitta** [EscVM/OIDv4_ToolKit#12]
@keldrom
Below is the script I have used to parse the bounding boxes for specific objects. It is not parsing all the bounding boxes.
For example,for object AXE, I was able to download 115 annotations for 115 images with your script. coming to my script, I was able to parse only for few images. Please correct me if I'm going wrong with my script.

import pandas as pd
import csv
df2=pd.read_csv('./train-annotations-bbox.csv',quoting=csv.QUOTE_NONE, error_bad_lines=False)
df1=pd.read_csv('class-descriptions-boxable.csv')

objlis=['Toy', 'Beer', 'Chopsticks', 'Towel', 'Glove', 'Sunglasses', 'Ball', 'Backpack', 'Headphones', 'Fast food', 'Screwdriver', 'Laptop', 'Person', 'Wrench', 'Flashlight', 'Scissors', 'Suitcase', 'Snack', 'Medical equipment', 'Cat', 'Computer mouse', 'Coin', 'Calculator', 'Box', 'Stapler', 'Drink', 'Ratchet', 'Hat', 'Eraser', 'Tin can', 'Mug', 'Can opener', 'Goggles', 'Coffee cup', 'Paper towel', 'Flying disc', 'Face powder', 'Fruit', 'Pillow', 'Hammer', 'Drinking straw', 'Hair dryer', 'Alarm clock', 'Knife', 'Bottle', 'Bottle opener', 'Dumbbell', 'Bowl', 'Musical instrument', 'Ring binder', 'Plate', 'Mobile phone', 'Crutch', 'Pencil case', 'Briefcase', 'Plastic bag', 'Sports equipment', 'Lipstick', 'High heels', 'Shotgun', 'Picture frame', 'Tripod', 'Picnic basket', 'Handbag', 'Toilet paper', 'Footwear', 'Tablet computer', 'Dog', 'Book', 'Axe', 'Flower', 'Spoon', 'Fork', 'Camera', 'Vegetable', 'Diaper', 'Envelope', 'Watch', 'Handgun', 'Facial tissue holder', 'Ruler', 'Luggage and bags', 'Umbrella', 'Glasses', 'Pen', 'Binoculars', 'Perfume', 'Remote control', 'Helmet']

df3=pd.merge(df1,df2,on='Class_id') #Created Columns 'Class_id' & 'class' in 'class-descriptions-boxable.csv'
print(df3)
for i in objlis:
mod=i
mod=df3[df3['class']==i]
#print(mod)
mod.to_excel(i+'.xlsx')

Please try this script on your computer once.

I printed the rows of train-annotations-bbox.csv file,it is showing me 1048575 rows x 14 columns
![screenshot from 2018-09-21 09-49-42](https://user-images.githubusercontent.com/11436918/45894714-0ad71280-bd84-11e8-8902-da2a059347e7.png)

Thanks.

**Comment by keldrom** [comment]
@jillelajitta why don't you have used our `get_labels` function and only re-write the part about the creation of .txt files?
Btw write the aim of your mod and we'll try to help you.

**Comment by jillelajitta** [comment]
I want the bounding box data in CSV files seperately for each object along with image height and width. So First I want to parse bounding boxes from train-annotations-bbox.csv file and then get the height and width from the images into those CSV files.

**Comment by keldrom** [comment]
@jillelajitta you need to read pandas documentation and see how to write on a new .csv files. Then you can change the write section of `get_labels` to this new ones maybe adding the info about height and widht that you can simply take with other library (I think cv2 has some useful features).

**Comment by keldrom** [comment]
@jillelajitta line 120 
`print(class_name, box[0], box[2], box[1], box[3], file=f)`

**Comment by jillelajitta** [comment]
Thank you so much, now I am able to grab everything I want. You are amazing studd!! :) :)
