### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by lalazari** [EscVM/OIDv4_ToolKit#13]
Hi, thanks for the work!

I am facing the following issue:

> python main.py downloader --classes backpack --type_csv all

[INFO] Downloading backpack.
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    class_code = df_classes[df_classes[1] == class_name].values[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Any help?

Thanks

**Comment by lalazari** [comment]
I just found that I have to use:

python main.py downloader --classes **B**ackpack --type_csv all
instead of
python main.py downloader --classes backpack --type_csv all

**Comment by shivagur** [comment]
python main.py downloader --classes Human face Vehicle registration plate --type_csv validation --limit 800

    [INFO] | Downloading Human.
Traceback (most recent call last):
  File "C:\Users\T7730OG\OIDv4_ToolKit\main.py", line 37, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "C:\Users\T7730OG\OIDv4_ToolKit\modules\bounding_boxes.py", line 56, in bounding_boxes_images
    class_code = df_classes.loc[df_classes[1] == class_name].values[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

I had tried changing all above mentioned stuff but no result.. help would be appreciated.
