### ISSUE TITLE
Can't download grape train set

### ISSUE THREAD

**Issue by navrajkambo** [EscVM/OIDv4_ToolKit#15]
I am able to download the grape test and validation sets using the command below.
``` python
python main.py downloader --classes Grape --type_csv validation
python main.py downloader --classes Grape --type_csv test
```
However, when i try and download the train set, the program hangs for a few seconds, and then fails with a memory error in pandas.
`python main.py downloader --classes Grape --type_csv train`
*Note: I'm running python 3 on windows*

Any help is appreciated, thanks.

**Comment by EscVM** [comment]
Hi @navrajkambo,

how much RAM do you have on your computer?

**Comment by navrajkambo** [comment]
I have 8GB of RAM, so the actual memory of my machine may not be the issue. 
![capture](https://user-images.githubusercontent.com/39748089/48450014-59d46f00-e759-11e8-8223-8146344aff87.PNG)

**Comment by navrajkambo** [comment]
Actually, you may be right. The 32-bit version of python is only allowed something like 2GB of RAM to work with, from what i've read online. My lab computer probably just needs to be updated to use the 64-bit version of python 3. I'll give it a try and hopefully that will resolve my issues. Thanks!

**Comment by navrajkambo** [comment]
Yea, issue resolved by using python-64 instead of python-32. Thanks!

**Comment by EscVM** [comment]
Nice!

**Comment by mikkleini** [comment]
I was using 64-bit Python and still got this error. What helps is using --n_threads argument with value less than 20 (which is default).
