### ISSUE TITLE
Typo in  README file in command line

### ISSUE THREAD

**Issue by Zhaans** [EscVM/OIDv4_ToolKit#17]
Hi Vittorio. Thanks for this cool tool, very helpful. Just want to notice that you have typo in your README file, when you give the command to download or visualize. Instead of using command `downloader` we should use `download`. The same with `visualizer`.

**Comment by EscVM** [comment]
I @Zhaans, thank you! I really appreciate it!

Thank for the tip, I'll change it. Originally it was like that but, then @keldrom decided to change it without updating the README file😈
