### ISSUE TITLE
Usage with v3 classes

### ISSUE THREAD

**Issue by dudeperfect95** [EscVM/OIDv4_ToolKit#23]
Is there any way to download and label image classes from v3 version? I change csv_folder content with files from v3, OID url to https://storage.googleapis.com/openimages/2017_11/, but for example downloading Chimney images it outputs:
[INFO] Downloading Chimney.
----------Chimney----------
[INFO] Downloading train images.
[INFO] Found 0 online images for train.
[INFO] All images already downloaded.
[INFO] Creating labels for Chimney of train.
[INFO] Labels creation completed.

**Comment by EscVM** [comment]
Hi @dudeperfect95 ! Do you need labels for object detection or mere classification?

**Comment by dudeperfect95** [comment]
Im interested in object detection

**Comment by EscVM** [comment]
I'm sorry, but that list contains also all the image-level classes that are much more than 600. You can easily check the different classes with the provided explore interface [link](https://storage.googleapis.com/openimages/web/visualizer/index.html?set=train&c=%2Fm%2F07cmd)

**Comment by EscVM** [comment]
This instead is the visualizer for the old dataset [link](https://storage.googleapis.com/openimages/web/visualizer/index.html?set=train&c=%2Fm%2F07cmd) (oidv3)

**Comment by dudeperfect95** [comment]
Oh now I get it. Whole day looking for specific v3 downloader. I was sure that v3 and v4 contains different objects. Thank you for explanation.

**Comment by EscVM** [comment]
You are welcome :+1:
