### ISSUE TITLE
What format are the labels in?

### ISSUE THREAD

**Issue by LukeAI** [EscVM/OIDv4_ToolKit#25]
What format are the labels in?
I'm seeing this:
Man   141.44 149.02449 636.16 684.36021
Man   414.08 117.68437 807.68 684.36021
Man   629.76 449.63126 1023.36 684.36021
Is is class x1 y1 x2 y2
or what...?

**Comment by EscVM** [comment]
Sorry for the late answer...

Anyway, on the README page you can find all the information you need :)
