### ISSUE TITLE
how to stop it?

### ISSUE THREAD

**Issue by thekhieu** [EscVM/OIDv4_ToolKit#29]
The tool  is downloading. But i wanna stop it. I was pressed Ctrl+C anytime but i can interrupt.
what need i do?

**Comment by keldrom** [comment]
It's impossible that the command Crtl+C doesn't stop the script: Btw you can also use Crtl+Z but I don't think this is a real problem.

**Comment by ohlr** [comment]
I have the same issue.

`python main.py downloader --classes Person Woman --type_csv validation --multiclasses 1 --n_threads 5`

```
cancelled: ctrl-c received
cancelled: ctrl-c received
cancelled: ctrl-c received
```
Afterwards the download print occurs again - it does not stop

**Comment by thekhieu** [comment]
Try ctrl+z
Được gửi từ iPhone của tôi

Vào ngày 1 thg 5, 2019, lúc 23:00, Oskar Haller <notifications@github.com> đã viết:

**Comment by ohlr** [comment]
`ctrl+z` works thanks 

still weird that `ctrl-c` is printed to the console but has no effect
