### ISSUE TITLE
Problem with classes containing a space

### ISSUE THREAD

**Issue by ivanovean** [EscVM/OIDv4_ToolKit#3]
Then class name contain space download directory also contain space.
So "aws s3 cp" command fails cause unable to parse path.

Sample: class_name=Vehicle registration plate
[INFO] Downloading Vehicle registration plate.
----------Vehicle registration plate----------
[INFO] Downloading all images.
[INFO] Found 3944 online images for train.
[INFO] Download of 3876 images in train.
  0%|                                                                                                                                                                                                      | 0/3876 [00:00<?, ?it/s]
Unknown options: registration,plate
  0%|                                                                                                                                                                                            | 1/3876 [00:01<1:16:07,  1.18s/it]
Unknown options: registration,plate

I create small merge request, thats  that fixes this problem:
https://github.com/EscVM/OIDv4_ToolKit/pull/2

**Comment by EscVM** [comment]
Yep, you are right @ivanovean. Thank you very much for your contribution. I'll check the code and if it works I'll merge the code.

**Comment by ivanovean** [comment]
And one more thing. visualize script also going wrong in the module 'show', then parsing lines of label file by whitespaces. 
Now there is no way to send one more commit, but I think you understand what I mean

**Comment by keldrom** [comment]
I've corrected the code. For class with space in use '_' instead of the space.
