### ISSUE TITLE
fatal error: An error occurred (404) when calling the HeadObject

### ISSUE THREAD

**Issue by skiler07** [EscVM/OIDv4_ToolKit#30]
Following the guide in the ReadMe, after:

```python3 main.py downloader_ill --sub m --classes Orange --type_csv train --limit 30```

I get the error:

```fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/0d72ff3e2601d71c.jpg" does not exist```

**Comment by keldrom** [comment]
I will check this issue but it's not due to us; it'sseems that the image `0d72ff3e2601d71c.jpg` is present on the csv file but it's not on the OIDv4 server.

**Comment by xjhjinhui** [comment]
`fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/008ffc177de7df6a.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/84ffcb484b539cc3.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/a3431b0e852fb1d2.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/1430988b4579ff81.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/033e768e14cb478f.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/3c661e2261729dc7.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/0c5de6c8d9b3f951.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/90205b1be6a28ea8.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/0f87f97ce40be3d6.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/0164ab3193141cca.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/00a211b44bf6afc9.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/327d70534aebe3a4.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/0daaf5dd8717625e.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/04d4ad1af0c59aed.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/2cee7cc932227aa3.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/07ddc7ad53e00557.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/317b17544b6bd5f6.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/a1c8d8c66a789a89.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/47a204860d9e15ce.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/02ed13ef8306c6ef.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/f6ff8098f22d760e.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/04809452f59472b9.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/1f11343542826c7d.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/192b23337fc44db7.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/03cce1578965c3b9.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/05a0f9598eef3ffa.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/009b8c5e8671f755.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/4535236f8e82ec31.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/041107324aad05c0.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/0775db402b857c66.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/8dc509f4f8218c7d.jpg" does not exist
fatal error: An error occurred (404) when calling the HeadObject operation: Key "train/1024d370ec1335c1.jpg" does not exist
`
I also get these error, could you tell me how can I solve it?

**Comment by taylor4712** [comment]
same issue
