### ISSUE TITLE
Annotation bounding box coordinates with invalid values?

### ISSUE THREAD

**Issue by monocongo** [EscVM/OIDv4_ToolKit#33]
I have downloaded images and label files for an image class, and I'm wondering if maybe I've done something to monkey with the bounding box coordinates in the label `*.txt` files.

For example, I have a label file (`0a7df07bbac03159.txt`) with the following contents:

```
Sword 14.72 7.68 669.44 767.360256
```

My understanding from the `README` is that the annotation bounding box coordinates should be within the normalized range [0, 1], but that's obviously not what I'm getting in my label files, as seen above.

Can anyone comment as to how I should interpret the bounding box values in the `*.tx` files, and/or what I've done wrong to get values that appear to be outside the expected range? Are the float values present in these files computed from the original/normalized bounding box values against the height/width of the corresponding image, and if I want to have the actual integer pixel numbers for the bounding box then I can just round these to the nearest integer? For example, the bounding box for the above would be (left_x=15, top_y=8, right_x=669, bottom_y=767)?

Thanks in advance for any comments or suggestions.

**Comment by EscVM** [comment]
Hi @monocongo!

You are right, the description is not anymore correct. Those are the values computed from the normalized images and so, as you wrote, the corresponding rounded values are (left_x=15, top_y=8, right_x=669, bottom_y=767).

**Comment by monocongo** [comment]
Thanks @EscVM !
