### ISSUE TITLE
Image level download for positive labels only

### ISSUE THREAD

**Issue by JustusWest** [EscVM/OIDv4_ToolKit#34]
Hi guys,
Love this library, it's super helpful and I've been using it to download images for my research project. I was downloading image level label images related to alcohol and noticed that an image will get downloaded into the directory corresponding to a label even if the label is negative for that image. ie an image where Beer=1 and Wine=0 in the train-annotations-human-imagelabels.csv will get downloaded in both the Beer and Wine directories. Is there a way to download images only into directories that correspond to positive labels?

**Comment by keldrom** [comment]
@JustusWest thank you for the appreciations :D
btw, if you write the command that u used I will try to understand the problem because the usage of the new dataset (with no bounding boxes) maybe made some new issues like this.

**Comment by JustusWest** [comment]
I used:
`python3 main.py downloader_ill --sub h --classes classes.txt --type_csv train`

**Comment by keldrom** [comment]
@JustusWest what's in your `classes.txt` files?

**Comment by JustusWest** [comment]
[classes.txt](https://github.com/EscVM/OIDv4_ToolKit/files/3099394/classes.txt)

**Comment by keldrom** [comment]
I think that you're .txt file could be like this:
`Beer
Wine
Alcohol
Non-alcoholic beverage`

Btw I think that there can be some "overlapping" on the datasets: i.e. a bottle of wine will be also into the dataset of Alcohol. So in this case there are no issues on our toolkit, it's the provided dataset that includes maybe the same image into the two different sub-dataset. So in this case is right the download of the same image into two different subset.
