### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by rahulroxx** [EscVM/OIDv4_ToolKit#36]
While downloading the images on windows machine it is throwing the below traceback: 

```
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "E:\python\experiment\OIDv4_ToolKit\modules\bounding_boxes.py", line 87, in bounding_boxes_images
    download(args, df_val, folder[i], dataset_dir, class_name, class_code)
  File "E:\python\experiment\OIDv4_ToolKit\modules\downloader.py", line 21, in download
    rows, columns = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by keldrom** [comment]
@rahulroxx that command is used to know the terminal size. Have you use the command prompt?

**Comment by keldrom** [comment]
meanwhile I solve the problem substitute the line 
`rows, columns = os.popen('stty size', 'r').read().split()`
with
`columns = 50`

**Comment by rahulroxx** [comment]
Yup sure, thanks for prompt response @keldrom

**Comment by rahulroxx** [comment]
I have like 4 classes in 

> classes-new.txt

```
Chair
Sofa
Dining_table
television
```

**Comment by keldrom** [comment]
I think I'm done. Download the new version of `downloader.py` and check.
If all works close this issue.

**Comment by rahulroxx** [comment]
Sure thanks for your support 👍
