### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by rahulroxx** [EscVM/OIDv4_ToolKit#37]
```
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "/mountdir/OIDv4_ToolKit/modules/bounding_boxes.py", line 56, in bounding_boxes_images
    class_code = df_classes.loc[df_classes[1] == class_name].values[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0


```

**Comment by rahulroxx** [comment]
While downloading multiple classes with `--classes=classes-new.txt`

> Bed
> Dining_table
> Microwave
> Chair

**Comment by keldrom** [comment]
Could you provide the full terminal command?

**Comment by keldrom** [comment]
In a few I will close this issue

**Comment by thurussian** [comment]
does anyone know what's the resolution to the bounding_boxes.py script error?!  I am still not sorted out.  I am getting exact print out as rahulroxx above single or multiple class

**Comment by IdrissouSOUNON** [comment]
> Pourriez-vous fournir la commande de terminal complète?

I have got the same error.

The command is `python main.py downloader --classes person --type_csv train --limit 20000`

**Comment by IdrissouSOUNON** [comment]
> Could you provide the full terminal command?

I have got the same error.

The command is python main.py downloader --classes person --type_csv train --limit 20000

**Comment by IdrissouSOUNON** [comment]
I see my mistake. The class name is incorrect. I should write `Person` instead of `person`.

**Comment by varun003** [comment]
> > Could you provide the full terminal command?
> 
> I have got the same error.
> 
> The command is python main.py downloader --classes person --type_csv train --limit 20000

Iam also getting the same error, there is no typing error also.
The command is : python main.py downloader  --classes Personal_flotation_device  --type_csv train  --limit 300

**Comment by Chaitanya-Thombare** [comment]
> 
> 
> > > Could you provide the full terminal command?
> > 
> > 
> > I have got the same error.
> > The command is python main.py downloader --classes person --type_csv train --limit 20000
> 
> Iam also getting the same error, there is no typing error also.
> The command is : python main.py downloader --classes Personal_flotation_device --type_csv train --limit 300

I am not an expert or experienced. But I have an observation which might help. I get the same error for
`py main.py downloader --classes Volleyball_(Ball) Tennis_ball  --type_csv train --limit 400` , 

but did not get that error for 
`py main.py downloader --classes Car --type_csv train --limit 4`

I think this doesn't work for some classes. Try to download some other class, like Car.

**Comment by AlexDavydov357** [comment]
This problem only with apostrophe. You need to change it from ' to " and everything will be okay. 
For example:
 `python main.py downloader --classes "Fire hydrant" "Traffic light" Car Bus --type_csv train --limit 400`

**Comment by Darmandran** [comment]
> > > Could you provide the full terminal command?
> > 
> > 
> > I have got the same error.
> > The command is python main.py downloader --classes person --type_csv train --limit 20000
> 
> Iam also getting the same error, there is no typing error also. The command is : python main.py downloader --classes Personal_flotation_device --type_csv train --limit 300

for some reason Personal_flotation_device is actually Lifejacket
python main.py downloader --classes Lifejacket --type_csv train --limit 300

**Comment by AlexDavydov357** [comment]
This is full command line, what I used. But actually I get any dataset different way. I not use this utils. This utils I tried just once for learning experiment and never used again.

**Comment by younes113** [comment]
> ```
> Traceback (most recent call last):
>   File "main.py", line 36, in <module>
>     bounding_boxes_images(args, DEFAULT_OID_DIR)
>   File "/mountdir/OIDv4_ToolKit/modules/bounding_boxes.py", line 56, in bounding_boxes_images
>     class_code = df_classes.loc[df_classes[1] == class_name].values[0][0]
> IndexError: index 0 is out of bounds for axis 0 with size 0
> ```

You should use capitol for classes names

**Comment by younes113** [comment]
> The command is python main.py downloader --classes person --type_csv train --limit 20000
use instead this command with capitol letters for classes name
The command is python main.py downloader --classes Person --type_csv train --limit 20000
