### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by santhoshsridhar0304** [EscVM/OIDv4_ToolKit#38]
Command: python main.py downloader --classes Shirt --type_csv all

StackTrace: 

[DOWNLOAD] \| File train-annotations-bbox.csv downloaded into OID\csv_folder\trai n-annotations-bbox.csv.                                                          Traceback (most recent call last):                                                 File "D:\Projects\Product Tagging\tensorflow1\addons\OIDv4_ToolKit\modules\dow nloader.py", line 25, in download                                                    columns, rows = os.get_terminal_size(0)                                      OSError: [WinError 6] The handle is invalid                                                                                                                       During handling of the above exception, another exception occurred:                                                                                               Traceback (most recent call last):                                                 File "main.py", line 36, in                                                bounding_boxes_images(args, DEFAULT_OID_DIR)                                   File "D:\Projects\Product Tagging\tensorflow1\addons\OIDv4_ToolKit\modules\bou nding_boxes.py", line 87, in bounding_boxes_images                                   download(args, df_val, folder[i], dataset_dir, class_name, class_code)         File "D:\Projects\Product Tagging\tensorflow1\addons\OIDv4_ToolKit\modules\dow nloader.py", line 27, in download                                                    columns, rows = os.get_terminal_size(1)                                      OSError: [WinError 6] The handle is invalid
--

**Comment by keldrom** [comment]
Already solved this issue. Download the latest version of the toolkit.

**Comment by AbdoElfathi** [comment]
still have the same issue :(

**Comment by Muzammil-Elahi** [comment]
I have the same issue

**Comment by debabratp** [comment]
I am using OID v4 locally. 
I too got the same error. 
I noticed that, using --limit option with value more than 8 resulted to this error. 
I think this error is related to System resource utilization.

My machine is having 8GB RAM and i7 4 core CPU .
