### ISSUE TITLE
wrong txt format for classes with underscore

### ISSUE THREAD

**Issue by ohlr** [EscVM/OIDv4_ToolKit#39]
`python main.py downloader --classes Human_face --type_csv 'validation' --multiclasses 1`

The txt label files look like the following:
`Human face 272.903578 214.58227200000002 448.06849 435.37612800000005`

According to the documentation there should be a underscore between human and face.

> However, in order to accomodate a more intuitive representation and give the maximum flexibility, every .txt annotation is made like:
> 
> name_of_the_class left top right bottom

This also causes the [OID_to_yolo_gist](https://gist.github.com/EscVM/b6e5d60343c88f358742aa9e0de2cc3f) to fail

**Comment by ohlr** [comment]
quick fix for the `to_yolo_gist` in line 177:
```
class_name = l.pop(0)
try:
    float(l[0])
except ValueError:
    class_name += ' ' + l.pop(0)
```

**Comment by EscVM** [comment]
Thank you for the hint! I'm sure it will be helpful for all yolo users.
