### ISSUE TITLE
Couldn't download images

### ISSUE THREAD

**Issue by KedarisettiSreeVamsi** [EscVM/OIDv4_ToolKit#41]
Since OID has migrated from oidv4 to oidv5 the aws is not working thereby the images are not getting downloaded please migrate this toolkit from oidv4 to oidv5 as soon as possible

**Comment by keldrom** [comment]
I will do it asap

**Comment by keldrom** [comment]
@KedarisettiSreeVamsi the downloader is working correctly because the v4 version of the dataset is still available
Btw I will upgrade our toolkit at v5 with instance segmentation asap

**Comment by KedarisettiSreeVamsi** [comment]
I will try again .
I have a question can we use it in colab

**Comment by keldrom** [comment]
?

**Comment by KedarisettiSreeVamsi** [comment]
Google Collaboratory

**Comment by KedarisettiSreeVamsi** [comment]
I have tried your toolkit in google colab and it didn't work

**Comment by keldrom** [comment]
I don't use it but using Jupyter is not possible to compile. Use a classsic terminal and all will works.
