### ISSUE TITLE
Add option to default prompts to "Yes"

### ISSUE THREAD

**Issue by monocongo** [EscVM/OIDv4_ToolKit#43]
First of all thanks for making this application available, it's quite helpful in my work creating datasets for inputs when training object detection models.

I would like to call this application from within a script. This is a bit tricky at the moment because I get various prompts asking me if I want to download missing files. This doesn't always occur (I'm not sure why) but when it does it requires keyboard input (I always choose yes). The prompt I'm seeing may be coming from [here](https://github.com/EscVM/OIDv4_ToolKit/blob/master/modules/csv_downloader.py#L32).

I would like to run this module's `main.py` script in a non-interactive mode where it always downloads any missing files without confirmation from the user. I don't see an option to disable confirmation prompts.

If someone can advise as to where to modify this code to allow for this then I am happy to make the changes myself and submit a PR once I've verified that it's working. My suggestion is to add a command line option such as `--yes` to disable confirmation, such as what's available on the [command line for conda](https://docs.conda.io/projects/conda/en/latest/commands/install.html#Output,%20Prompt,%20and%20Flow%20Control%20Options) (as an example).

Thanks in advance for any assistance with this issue.

**Comment by cdleong** [comment]
I think we'd need to edit the [https://github.com/EscVM/OIDv4_ToolKit/blob/93954cad4884ca8c1277ece6a9a786235ac2f569/modules/parser.py#L8 code, adding something like --autodownload or --yes.

Then pass that to the error_csv function here: https://github.com/EscVM/OIDv4_ToolKit/blob/93954cad4884ca8c1277ece6a9a786235ac2f569/modules/bounding_boxes.py#L53

And finally edit this bit to take in that variable and skip the prompt if it's set to yes: https://github.com/EscVM/OIDv4_ToolKit/blob/93954cad4884ca8c1277ece6a9a786235ac2f569/modules/csv_downloader.py#L24

**Comment by cdleong** [comment]
Specifically, I think I'd edit this:

https://github.com/EscVM/OIDv4_ToolKit/blob/93954cad4884ca8c1277ece6a9a786235ac2f569/modules/csv_downloader.py#L24

to this:
```
 def error_csv(file, csv_dir, autodownload=yes): 
```

and then this:
```
        print(bc.FAIL + "Missing the {} file.".format(os.path.basename(file)) + bc.ENDC)
        ans = input(bc.OKBLUE + "Do you want to download the missing file? [Y/n] " + bc.ENDC)

        if ans.lower() == 'y':
            folder = str(os.path.basename(file)).split('-')[0]
            if folder != 'class':
                FILE_URL = str(OID_URL + folder + '/' + file)
            else:
                FILE_URL = str(OID_URL + file)
```

to this:
```
        print(bc.FAIL + "Missing the {} file.".format(os.path.basename(file)) + bc.ENDC)
        if autodownload:
            ans = 'y'
        else:
            ans = input(bc.OKBLUE + "Do you want to download the missing file? [Y/n] " + bc.ENDC)


        if ans.lower() == 'y':
            folder = str(os.path.basename(file)).split('-')[0]
            if folder != 'class':
                FILE_URL = str(OID_URL + folder + '/' + file)
            else:
                FILE_URL = str(OID_URL + file)
```

**Comment by cdleong** [comment]
... or you could use try the "yes" utility. 

For example...
```
yes|python main.py downloader --type_csv all --classes Flower
```

**Comment by pic4seradmin** [comment]
Thank you for your appreciations :D I will add this feature in the next release.

**Comment by keldrom** [comment]
Thank you for your appreciations :D I will add this feature in the next release

**Comment by keldrom** [comment]
Done.

**Comment by monocongo** [comment]
You guys rock, thanks a lot for this!
