### ISSUE TITLE
download multiclass images

### ISSUE THREAD

**Issue by wang5566** [EscVM/OIDv4_ToolKit#5]
I want to know how I can download many classes images together, such as 1000 classes. The parameter "class" how can i set?

**Comment by EscVM** [comment]
Hi, @wang5566. This toolkit handles the dataset for object detection that has 600 classes. Instead the image level labels dataset, for classification, has much more classes, mostly machine generated, but you can't use this toolkit to download them. [Here](https://storage.googleapis.com/openimages/web/factsfigures.html)  you can find more information about the dataset and [here](https://storage.googleapis.com/openimages/web/download.html) you can download the image level labels dataset.

**Comment by wang5566** [comment]
thank you for your reply. But I download the train-annotations-human-imagelabels.csv from "Subset with Image-Level Labels " Human Verified labels train, and i only include Image ID,  source LabelName and Confidence. How can I download images?

**Comment by wang5566** [comment]
I got the answer, thank you
