### ISSUE TITLE
[ERROR] | Missing the class-descriptions-boxable.csv file.

### ISSUE THREAD

**Issue by Pari-singh** [EscVM/OIDv4_ToolKit#50]
Hi, 

I want to download Man, Woman data and using this line:
python main.py downloader --classes Man Woman --multiclasses 1 --type_csv all

I get the error Missing class-description-boxable.csv and train-annotations-bbox.csv.

I assume train-annotations-bbox.csv is an important file and thus would be required. Any solution to this?

**Comment by keldrom** [comment]
Just say `y` and the toolkit will download it

**Comment by 1319722602** [comment]
how can i solve it ,please,

**Comment by 1319722602** [comment]
I want to downloader -- classes Apple Orange --type_csv all , but I get "[ERROR] | Missing the class-descriptions-boxable.csv file." .
