### ISSUE TITLE
.gitignore doesn't appear to be valid

### ISSUE THREAD

**Issue by monocongo** [EscVM/OIDv4_ToolKit#53]
Rather than being a valid `.gitignore` the file in place appears to a page that was copied as HTML. Replace with a valid `.gitignore`, perhaps from the GitHub template provided for Python.

**Comment by keldrom** [comment]
I will do it asap

**Comment by monocongo** [comment]
This fix, as well as all the work required for adding this package to PyPI, is available in PR #54, it just needs to be reviewed and merged.
