### ISSUE TITLE
How can I download images with more than one class and get all classes bounding boxes, in the corresponding notation text file ? 

### ISSUE THREAD

**Issue by sc4321** [EscVM/OIDv4_ToolKit#55]
For example, if there is an image of a Person riding a Bicycle, I would like to get 2 bounding box data of the Person and the Bicycle.

**Comment by sc4321** [comment]
For example, if there is an image of a Person riding a Bicycle, I would like to get 2 bounding box data of the Person and the Bicycle.

**Comment by sc4321** [comment]
Closed by mistake...

**Comment by glenn-jocher** [comment]
+1 I need this also.

**Comment by keldrom** [comment]
I'm sorry but this option is not considered. You can use `--multiclasses` but it will produce different .txt files one for each class

**Comment by Anas-Alshaghouri** [comment]
Hello
Any update on this issue?

**Comment by sc4321** [comment]
NOP...
