### ISSUE TITLE
I made YOLO annotations script

### ISSUE THREAD

**Issue by galaktyk** [EscVM/OIDv4_ToolKit#6]
[here](https://gist.github.com/galaktyk/8fbf80c2c66fcbde8e641c2d5f9bf939)
It create .txt yolo format annotation out from downloaded images
compatible with other visualizer e.g. [labelImg](https://github.com/tzutalin/labelImg), [boobs](https://github.com/drainingsun/boobs)

*now read .csv in small chunk so it wont crash my potato PC  and re-arrange if condition to improve speed.

**Comment by EscVM** [comment]
Hi @galaktyk,
I've just upadated the "oid to yolo" script. It has far more features than the previous version, but it still can be improved.
**Feature**
Convert:
- convert one class to yolo format
- convert multiple classes in a common folder to yolo format
- copy all pictures together with the new created labels
- create the .name file with the classes

Dummy:
- add to the converted folder, pictures of a different class with void labels. It's helpful to had negative examples to the dataset

Enjoy  [;)](https://gist.github.com/EscVM/b6e5d60343c88f358742aa9e0de2cc3f)

**Comment by pullmyleg** [comment]
@EscVM just a note there is a small issue with the latest version. The previous version works fine. 

  File "oid_to_yolo.py", line 177
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation

Thanks for the great tools!
