### ISSUE TITLE
How long does it takes to download single class images?

### ISSUE THREAD

**Issue by owlisie** [EscVM/OIDv4_ToolKit#60]
I started to download 'Person' class train images like 14 hours ago and it still go for 75% completed. I just wonder how long does it takes for others.
I'm not very familiar with data issues so not that sure what could I do for speed accelerate.
Can I use GPU to make download faster? Or is it normal speed to others too?
Btw thanks for the toolkit. It really helps me.

**Comment by taylor4712** [comment]
Maybe you can try it on Google Colab. 
Open a new Notebook. Edit --> Notebook settings --> Hardware accelerator --> GPU

**Comment by owlisie** [comment]
> Maybe you can try it on Google Colab.
> Open a new Notebook. Edit --> Notebook settings --> Hardware accelerator --> GPU

Gonna try, thanks! @taylor4712
