### ISSUE TITLE
How to download a class with two words?

### ISSUE THREAD

**Issue by sliawatimena** [EscVM/OIDv4_ToolKit#64]
Dear all,

I need to download classes with two words, e.g.: Human mouth, Human head, etc.
I try using space or _ (underscore) with no luck.
Thank you very much in advance.

Warmest Regards,
Suryadi

**Comment by gucchilight** [comment]
Did you solve this issue ?

**Comment by sliawatimena** [comment]
Dear all,

Now I can download Human_head, Human_face, Human_mouth, etc

$ python3 main.py downloader --classes Human_face --type_csv all

thank you very much.

warmest regards,
suryadi
