### ISSUE TITLE
Support for Filtering Image-Level Labels 

### ISSUE THREAD

**Issue by mylyu** [EscVM/OIDv4_ToolKit#8]
Hi, thanks for the great toolkit. Is it possible to download images based on image-level labels (19,995 classes), rather than the 600 boxable classes only? I have downloaded the csv needed.

**Comment by mylyu** [comment]
> @mylyu thx for your support :)
> Your request is the next evolution of our toolkit. I think I can work on it during this week. Stay tuned ;)

That's great.

**Comment by keldrom** [comment]
I'm sorry but this period is dark and full of terrors. I will produce the new release of the toolkit ASAP.

**Comment by zaichang** [comment]
@keldrom I'm also trying to use the toolkit to download images for a classifier rather than object detection. By modifying main.py I was able to download images from the image-level label classes (though with many urls that resulted in 404). Did you ever find a solution to filtering images with a certain confidence?

@mylyu Are you taking pull requests for this library? If so, maybe we can help with increasing it's capabilities

**Comment by mylyu** [comment]
> @keldrom I'm also trying to use the toolkit to download images for a classifier rather than object detection. By modifying main.py I was able to download images from the image-level label classes (though with many urls that resulted in 404). Did you ever find a solution to filtering images with a certain confidence?
> 
> @mylyu Are you taking pull requests for this library? If so, maybe we can help with increasing it's capabilities

@zaichang I had a quick and dirty implementation for downloading image-level labels, but unfortunately I don't have time to clear things up and make a pull request.

**Comment by keldrom** [comment]
I will try to work on it this week, if I will enough free time.
If you can @zaichang send to me your draft and I will use it as starting point :)

**Comment by zaichang** [comment]
I cobbled it together, but I can spend some time this weekend to clean it up for a pull request. Works for you?
(Nice Marvin icon btw)

**Comment by keldrom** [comment]
@zaichang don't worry. I'm working on the implementation :)

**Comment by keldrom** [comment]
@zaichang @mylyu 
https://github.com/EscVM/OIDv4_ToolKit#download-images-from-image-level-labels-dataset

It's done! :D

I will close this issue. For any other problem don't hesitate and contact us.
