### ISSUE TITLE
Instance Segmentation 

### ISSUE THREAD

**Issue by faresbs** [EscVM/OIDv4_ToolKit#93]
Hello,

Is there a way to download the images from the Open Images Dataset v6 dataset with their Object Segmentation annotations?

I appreciate your help in advance.

**Comment by Sadam1195** [comment]
Did you find any solution for that? @faresbs

**Comment by whitenightwu** [comment]
> Did you find any solution for that? @faresbs

u can use 'fiftyone'. like
```
import fiftyone as fo
import fiftyone.zoo as foz
dataset = foz.load_zoo_dataset(
    "open-images-v6",
    splits=("train", "validation", "test"),
    label_types=["segmentations"],
    classes = ['Apple', 'Grape', 'Strawberry', 'Lemon'],
    #max_samples=3000,
    seed=51,
    shuffle=True
)

```
